apiVersion: v1
kind: ConfigMap
metadata:
  name: roles-anywhere-config
data:
  APP_MESSAGE: Hello world from Vault Secrets Operator and IAM Roles Anywhere
  AWS_REGION: us-east-2
  AWS_PROFILE_ARN: arn:aws:rolesanywhere:us-east-2:111122223333:profile/REPLACE_ME
  AWS_ROLE_ARN: arn:aws:iam::111122223333:role/HCPVaultAssumeRoleForTeam1App1
  AWS_TRUST_ANCHOR_ARN: arn:aws:rolesanywhere:us-east-2:111122223333:trust-anchor/REPLACE_ME
