apiVersion: v1
kind: Secret
metadata:
  name: vault-server-tls
  namespace: roles-anywhere-demo
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDLTCCAhWgAwIBAgIUOM0/mzXlzVZiPEcTNIBs31hr7NMwDQYJKoZIhvcNAQEL
    BQAwFjEUMBIGA1UEAxMLZXhhbXBsZS5jb20wHhcNMjYwNDE0MTgyMzI0WhcNMjcw
    NDE0MTgyMzU0WjAmMSQwIgYDVQQDExtleGFtcGxlLmNvbSBJbnRlcm1lZGlhdGUg
    Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDIsE2gt3yOZnty9Jiv
    YRk5E5Q/TdTqgLV2FGa5NAcV6d/E50VdhCjrtZlvbO7cDHaB2ioflLbylNPPBk+s
    fNS3rOrNsw/l7FYxiQPDGaNhngaX7Q3BFEmjHA+oUoL/k4+MvCzBEG894mR1qCsr
    p0lCahMwmSJztIX7cJTQ12+GGqrj0Cwd3vQMUgQo66xuT4/x60ZQuMx4LGKkOv3m
    MWGPzrDNi0WU5EDaINAdU7xGPoo0vnEz/cEwiCfw8w2h3KVI8NDKIKfPJ7z+Ig/Q
    RnCVRo7cQvS6WKdv3oYBr5CAvA5GurgT4Xwh1dcQGebh8+zjPHKt6XVJginCoDLp
    DsPvAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0G
    A1UdDgQWBBSExoeS6LAahTMxBR8GsbF9ZSZlEzAfBgNVHSMEGDAWgBRmG3KUHJZI
    Uf/WAUGhaFHZqKCr6zANBgkqhkiG9w0BAQsFAAOCAQEAy7gFb2noG7Nv40c5RPoV
    MjoivE9o5dNAjutdl3PHHwqls7SerkinO5xOljHDDoLp7ReBWZUG4BZ+jKEktZNm
    ztupF/VX8ETq7ZciUlzJwr7Hyq3xkRzci1+7/cKgbkud0cm27wzza6HpV69suwQ/
    L9lmDevwTifk4KDeYOWESkiRaU9QAdl7f1T+Jkf1FBGbdO7I8dchNqH134WfYTto
    D91guuvgmYn9wCotQ12pmVFFdQvqLh/ugKn4VOEWcPxfPZ3RxJLGHHOs4kZkwkkf
    aRX0RpQBTvR/Rjl9p59nabdF715qkDV3beqwDIRCLLIKeERwDU4wYGftDUPcp+B7
    yQ==
    -----END CERTIFICATE-----
