apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: roles-anywhere-client-cert
spec:
  vaultAuthRef: roles-anywhere-auth
  mount: pki-aws-int
  role: team1
  uriSans:
    - spiffe://example/Team1/App1/hello-world
  format: pem
  ttl: 30m
  expiryOffset: 5m
  revoke: false
  clear: true
  destination:
    create: true
    name: roles-anywhere-client-cert
    type: kubernetes.io/tls
