apiVersion: v1
kind: Secret
metadata:
  name: vault-server-tls
  namespace: roles-anywhere-demo
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_ME
    -----END CERTIFICATE-----
