apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: roles-anywhere-auth
spec:
  vaultConnectionRef: roles-anywhere-vault
  method: jwt
  mount: VAULT_AUTH_MOUNT_PLACEHOLDER
  namespace: VAULT_NAMESPACE_PLACEHOLDER
  jwt:
    role: VAULT_AUTH_ROLE_PLACEHOLDER
    serviceAccount: VAULT_AUTH_SERVICE_ACCOUNT_PLACEHOLDER
    audiences:
      - VAULT_AUTH_AUDIENCE_PLACEHOLDER
    tokenExpirationSeconds: 600
