apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: roles-anywhere-client-cert
spec:
  vaultAuthRef: roles-anywhere-auth
  mount: VAULT_PKI_MOUNT_PLACEHOLDER
  role: VAULT_PKI_ROLE_PLACEHOLDER
  uriSans:
    - SPIFFE_URI_PLACEHOLDER
  format: pem
  ttl: 30m
  expiryOffset: 5m
  revoke: false
  clear: true
  destination:
    create: true
    name: roles-anywhere-client-cert
    type: kubernetes.io/tls
